<?php

/**
 * Implements hook_views_data_alter().
 * 
 * @param array $data
 */
function views_daterange_filters_views_data() {
  
  /*
   $data = [];
  $data['views']['views_daterange_filters_daterange'] = [
    'title' => t('Date range filter'),
    'filter' => [
      'title' => t('Date range filter'),
      'group' => 'Date',
      'help' => t('Filter on a date range.'),
      'id' => 'views_daterange_filters_daterange'
    ],
  ];
   * 
   */
  //return $data;

}


/**
 * Implements hook_views_data_alter().
 */
function views_daterange_filters_field_views_data_alter(array &$data, \Drupal\field\FieldStorageConfigInterface $field_storage) {
  if ($field_storage->getType() === 'daterange') {
    foreach ($data as $field_name => $field) {
      foreach ($field as $key => $item) {
        //kint($key);
        
        if (substr($key, -10) === '_end_value') {
          //kint($field);
          
          if (isset($item['filter'])) {
            //$data[$field_name][$key] = $data[$field_name][$key];
            //kint($data[$field_name][$key]);
            $data[$field_name][$key]['filter']['id'] = 'views_daterange_filters_daterange';
            //kint($data[$field_name][$key]);
              
          //  kint($data[$field_name][$key . '_range']);
            //$data[$field_name][$key]['title'] .= ' Date Range';
            
            //kint($field_name);
            //kint($data[$field_name][$key . '_range']);
            //kint($data[$field_name][$key]);
          }
          
        }
        
      }
    }
  }
}
